### ISSUE TITLE
Constant stream data of all sensors and taxels

### ISSUE THREAD

**Issue by rzenha** [mcsix/xela-server-ros#1]
It seems the topic /xServTopic is no longer being published with the stream of data from all sensors and taxels. 
Is it possible to have this functionality back?

**Comment by mcsix** [comment]
should be fixed in the latest commit [93c52d8567a7410bb59721b2259c01d451434f97](https://github.com/mcsix/xela-server-ros/commit/93c52d8567a7410bb59721b2259c01d451434f97)

Please rebuild/source as usual and try again.
Please report back to let me know if it works on your system or not.
Thanks

**Comment by rzenha** [comment]
Thank you! I've tested it on my system and this seems to be working now
