### ISSUE TITLE
No valid XCAL data for XR1844

### ISSUE THREAD

**Issue by Legendaryaaa** [mcsix/xela-server-ros#4]
ubuntu20.04
./xels_server
get:
[warning]No valid XCAL data for XR1844

**Comment by Legendaryaaa** [comment]
./xela_conf
get:
[conf]CAN Server stopped

**Comment by Legendaryaaa** [comment]
I can't get the data of uskin. What's the reason?

**Comment by Legendaryaaa** [comment]
I can't get the data of uskin. What's the reason?

**Comment by mcsix** [comment]
To get a better overview of the issue, can you please submit the following files:

- /etc/xela/LOG/xela_server.log
- /etc/xela/xServ.ini
- 10 seconds of candump output

If you have tried candump before, and it has been empty, you might need to check the cables connected to the sensors and power them with the __external__ USB power supply (the controllers will not operate under 5.00V)

The warning you are getting is that the set sensor, XR1844, does not have calibration parameters. The current release of xela_conf will default to the old sensor and be switched out for the correct one in the next (1.7.6) release.
If you have recently bought the sensor, please edit the /etc/xela/xServ.ini file manually by changing the model from XR1844 to the following:

- XR2144 - if the sensor does not have any calibration meant for it (2021 - early 2022)
- XR2244 - if you are using standard calibration (2022 - _current_)
- __serial__ - if you have custom calibration, then the serial number (in such case, we should have also sent the necessary xeladef and xcal files to you)

Also, to note, this repository is for the ROS node, so preferably, all software-related questions should be sent to matthias@xelarobotics.com

**Comment by Legendaryaaa** [comment]
您发送的文件已收到~

**Comment by Legendaryaaa** [comment]
thank you,I will send the question to matthias@xelarobotics.com.
Now I can see the senors data by using ./xela_viz in  /etc/xela/

**Comment by Legendaryaaa** [comment]
anjing@anjing:~/project/tactile$ roslaunch xela_server service.launch
... logging to /home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/roslaunch-anjing-5454.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://anjing:39333/

SUMMARY
========

PARAMETERS
 * /param: 3
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    xela_server (xela_server/xela_server)
    xela_service (xela_server/xela_service)

auto-starting new master
process[master]: started with pid [5462]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 72da8030-a914-11ed-8ea9-bb614e9c30ee
process[rosout-1]: started with pid [5472]
started core service [/rosout]
process[xela_server-2]: started with pid [5475]
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f: command not found
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port 5000: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port 5000 --ip: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port 5000 --ip 192.168.1.149: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port 5000 --ip 192.168.1.149 __name:=xela_server: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 6: echo -f /etc/xela/xServ.ini --port 5000 --ip 192.168.1.149 __name:=xela_server __log:=/home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/xela_server-2.log: No such file or directory
/home/anjing/project/tactile/src/xela_server/scripts/xela_server: line 8: xela_server: command not found
process[xela_service-3]: started with pid [5486]
================================================================================REQUIRED process [xela_server-2] has died!
process has died [pid 5475, exit code 127, cmd /home/anjing/project/tactile/src/xela_server/scripts/xela_server -f /etc/xela/xServ.ini --port 5000 --ip 192.168.1.149 __name:=xela_server __log:=/home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/xela_server-2.log].
log file: /home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/xela_server-2*.log
Initiating shutdown!
================================================================================
[xela_service-3] killing on exit
[xela_server-2] killing on exit
Traceback (most recent call last):
  File "/home/anjing/project/tactile/src/xela_server/scripts/xela_service", line 14, in <module>
    import rospy  
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**xela_server: command not found** 
There is anthor question about xela-server-ros, as shown above，I have installed the software in /etc,and the PATH of xelaServ.ini is set as launch file, which is /etc/xela/selaServ.ini

**Comment by Legendaryaaa** [comment]
> anjing@anjing:~/project/tactile$ roslaunch xela_server service.launch ... logging to /home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/roslaunch-anjing-5454.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://anjing:39333/
> # SUMMARY
> 
> PARAMETERS
> 
>     * /param: 3
> 
>     * /rosdistro: noetic
> 
>     * /rosversion: 1.15.14
> 
> 
> NODES / xela_server (xela_server/xela_server) xela_service (xela_server/xela_service)
> # auto-starting new master
> process[master]: started with pid [5462]
> ROS_MASTER_URI=http://localhost:11311
> setting /run_id to 72da8030-a914-11ed-8ea9-bb614e9c30ee
> process[rosout-1]: started with pid [5472]
> started core service [/rosout]
> process[xela_server-2]: started with pid [5475]
> ~/src/xela_server/scripts/xela_server: line 6: xela_server: command not found
> process[xela_service-3]: started with pid [5486]
> ================================================================================REQUIRED process [xela_server-2] has died!
> process has died [pid 5475, exit code 127, cmd ~src/xela_server/scripts/xela_server -f /etc/xela/xServ.ini --port 5000 --ip 192.--.---.- __name:=xela_server __log:=/home/anjing/.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/xela_server-2.log].
> log file: ~.ros/log/72da8030-a914-11ed-8ea9-bb614e9c30ee/xela_server-2*.log
> Initiating shutdown!
> 
> [xela_service-3] killing on exit [xela_server-2] killing on exit Traceback (most recent call last): File "/actile/src/xela_server/scripts/xela_service", line 14, in import rospy File "/opt/ros/noetic/lib/python3/dist-packages/rospy/**init**.py", line 47, in from std_msgs.msg import Header File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/**init**.py", line 1, in from ._Bool import * File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in import genpy File "/opt/ros/noetic/lib/python3/dist-packages/genpy/**init**.py", line 34, in from . message import Message, SerializationError, DeserializationError, MessageException, struct_I File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in import numpy as np File "/usr/lib/python3/dist-packages/numpy/**init**.py", line 142, in from . import core File "/usr/lib/python3/dist-packages/numpy/core/**init**.py", line 17, in from . import multiarray File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in from . import overrides File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in from numpy.core._multiarray_umath import ( KeyboardInterrupt [rosout-1] killing on exit [master] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done
> 
> **xela_server: command not found** There is anthor question about xela-server-ros, as shown above，I have installed the software in /etc,and the PATH of xelaServ.ini is set as launch file, which is /etc/xela/selaServ.ini
